version: '3'
services:
  zora-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    image: zora-server:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  zora-front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8501:8501"
    image: zora-front:latest
