FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

COPY . /app
RUN apt-get update && apt-get install -y git && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir ftfy regex tqdm fastapi python-multipart uvicorn[standard] git+https://github.com/openai/CLIP.git
RUN apt-get remove -y git && apt-get autoremove -y
WORKDIR /app
CMD ["python", "-m", "uvicorn", "server_main:app", "--host", "0.0.0.0", "--port", "8000"]